name: mythtv
version: 1
summary: mythtv full build
description: First try at a myth build with front and backends and all build deps
confinement: devmode

apps:
    mythtv-frontend:
        command: desktop-launch mythfrontend
        plugs: 
          - network
          - x11
          - pulseaudio
          - opengl
          - optical-drive

parts:
    mythtv-frontend:
        plugin: autotools
        configflags:
          - --compile-type=release
          - --runprefix=/snap/mythtv/current/  # Is this valid
          - --disable-mythlogserver
          - --enable-crystalhd
          - --enable-lirc
          - --enable-audio-alsa
          - --enable-audio-oss
          - --enable-dvb
          - --enable-ivtv
          - --enable-firewire
          - --enable-joystick-menu
          - --with-bindings=perl
          - --enable-ffmpeg-pthreads
          - --enable-pic
          - --perl-config-opts="INSTALLDIRS=vendor"
          - --enable-libvpx
          - --enable-sdl
          - --enable-libmp3lame
          - --enable-libx264
          - --enable-vdpau
        source: https://github.com/MythTV/mythtv.git
        source-type: git
        source-branch: fixes/0.28
        source-subdir: mythtv
        install-via: prefix
        build-packages:  #  Starting with all the build deps and I will trim it down once it's building
            -   ccache
            -   make
            -   cmake
            -   autotools-dev
            -   autoconf
            -   automake
            -   build-essential
            -   dh-systemd
            -   fftw-dev
            -   fftw2
            -   hello
            -   help2man
            -   libasound2-dev
            -   libass-dev
            -   libavahi-client-dev
            -   libavahi-common-dev
            -   libavahi-compat-libdnssd-dev
            -   libavahi-compat-libdnssd1
            -   libavc1394-dev
            -   libbz2-dev
            -   libcaca-dev
            -   libcdaudio-dev
            -   libcdaudio1
            -   libcdio-cdda-dev
            -   libcdio-dev
            -   libcdio-paranoia-dev
            -   libcdparanoia-dev
            -   libcec-dev
            -   libcec-platform1v5
            -   libcec3
            -   libclass-data-inheritable-perl
            -   libclass-dbi-perl
            -   libclass-factory-util-perl
            -   libclass-inspector-perl
            -   libclass-singleton-perl
            -   libclass-trigger-perl
            -   libconvert-binhex-perl
            -   libcrystalhd-dev
            -   libdate-manip-perl
            -   libdatetime-format-builder-perl
            -   libdatetime-format-iso8601-perl
            -   libdatetime-format-strptime-perl
            -   libdatetime-locale-perl
            -   libdatetime-perl
            -   libdatetime-timezone-perl
            -   libdbd-mysql-perl
            -   libdbi-perl
            -   libdbix-contextualfetch-perl
            -   libdca-dev
            -   libdts-dev
            -   libdvdnav-dev
            -   libdvdread-dev
            -   libexif-dev
            -   libexiv2-dev
            -   libfaad-dev
            -   libfftw3-bin
            -   libfftw3-dev
            -   libfftw3-long3
            -   libfftw3-quad3
            -   libflac-dev
            -   libfribidi-dev
            -   libfstrcmp0
            -   libgif-dev
            -   libgif7
            -   libhwloc5
            -   libibverbs1
            -   libid3tag0-dev
            -   libiec61883-dev
            -   libima-dbi-perl
            -   libimage-size-perl
            -   libimlib2
            -   libimlib2-dev
            -   libio-sessiondata-perl
            -   libio-stringy-perl
            -   libjbig-dev
            -   libjpeg-dev
            -   libjpeg-turbo8-dev
            -   libjpeg8-dev
            -   libjson-perl
            -   liblircclient-dev
            -   libltdl-dev
            -   liblzma-dev
            -   libmad0-dev
            -   libmime-tools-perl
            -   libmodule-implementation-perl
            -   libmodule-runtime-perl
            -   libmp3lame-dev
            -   libmysqlclient-dev
            -   libmysqlclient20
            -   libnet-upnp-perl
            -   libogg-dev
            -   libopenmpi1.10
            -   libossp-uuid-perl
            -   libossp-uuid16
            -   libpackage-deprecationmanager-perl
            -   libpackage-stash-perl
            -   libparams-classify-perl
            -   libparams-util-perl
            -   libparams-validate-perl
            -   libpulse-dev
            -   libqt5opengl5-dev
            -   libqt5quickparticles5
            -   libqt5quickwidgets5
            -   libqt5script5
            -   libqt5scripttools5
            -   libqt5webkit5-dev
            -   libraw1394-dev
            -   libsdl1.2-dev
            -   libset-scalar-perl
            -   libslang2-dev
            -   libsoap-lite-perl
            -   libsub-install-perl
            -   libtag1-dev
            -   libtask-weaken-perl
            -   libtiff5-dev
            -   libtiffxx5
            -   libtry-tiny-perl
            -   libudev-dev
            -   libuniversal-moniker-perl
            -   libva-dev
            -   libva-drm1
            -   libva-egl1
            -   libva-glx1
            -   libva-tpi1
            -   libva-wayland1
            -   libva-x11-1
            -   libvdpau-dev
            -   libvisual-0.4-dev
            -   libvorbis-dev
            -   libvpx-dev
            -   libx264-dev
            -   libxml-libxml-perl
            -   libxml-namespacesupport-perl
            -   libxml-sax-base-perl
            -   libxml-sax-perl
            -   libxml-simple-perl
            -   libxml-xpath-perl
            -   libxv-dev
            -   libxvmc-dev
            -   libxinerama-dev
            -   mysql-common
            -   php
            -   php-common
            -   php7.0
            -   php7.0-cli
            -   php7.0-common
            -   php7.0-fpm
            -   php7.0-json
            -   php7.0-opcache
            -   php7.0-readline
            -   python-mysqldb
            -   python-pycurl
            -   python-urlgrabber
            -   qtdeclarative5-dev
            -   qtscript5-dev
            -   x11proto-video-dev
            -   yasm
        stage-packages:
            -   libqt5gui5
            -   libx11-xcb1
            -   libmysqlclient20
            -   libnotify-bin
            -   adduser
            -   zenity
            -   gksu
            -   wmctrl
            -   libxml-simple-perl
            -   libwww-perl
            -   libmyth-python
            -   transcode
            -   python
            -   python-imdbpy
            -   libqt5sql5-mysql
            -   libgl1-mesa-dri
            #-   iputils-ping
        after: [ desktop/qt5 ]

